### ISSUE TITLE
Crash on Servers

### ISSUE THREAD

**Issue by DeltaWolf7** [yoshisman8/ars-armiger#1]
Minecraft: 1.19.2
Forge: 43.2.4
Mod: 1.1

-- Head --
Thread: main
Stacktrace:
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:141) ~[securejarhandler-2.1.4.jar:?] {}
-- MOD ars_armiger --
Details:
	Caused by 0: java.lang.NoClassDefFoundError: net/minecraft/client/gui/GuiComponent
		at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?] {}
		at java.lang.ClassLoader.defineClass(ClassLoader.java:1012) ~[?:?] {}
		at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:119) ~[securejarhandler-2.1.4.jar:?] {}
		at cpw.mods.cl.ModuleClassLoader.lambda$findClass$15(ModuleClassLoader.java:219) ~[securejarhandler-2.1.4.jar:?] {}
		at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:229) ~[securejarhandler-2.1.4.jar:?] {}
		at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:219) ~[securejarhandler-2.1.4.jar:?] {}
		at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:135) ~[securejarhandler-2.1.4.jar:?] {}
		at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] {}
		at net.minecraftforge.eventbus.EventSubclassTransformer.buildEvents(EventSubclassTransformer.java:92) ~[eventbus-6.0.3.jar%2351!/:?] {}
		at net.minecraftforge.eventbus.EventSubclassTransformer.transform(EventSubclassTransformer.java:44) ~[eventbus-6.0.3.jar%2351!/:?] {}
		at net.minecraftforge.eventbus.EventBusEngine.processClass(EventBusEngine.java:26) ~[eventbus-6.0.3.jar%2351!/:?] {}
		at net.minecraftforge.eventbus.service.ModLauncherService.processClassWithFlags(ModLauncherService.java:32) ~[eventbus-6.0.3.jar%2351!/:6.0.3+6.0.3+master.039e4ea9] {}
		at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88) ~[modlauncher-10.0.8.jar%2354!/:?] {}
		at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-10.0.8.jar%2354!/:?] {}
		at cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50) ~[modlauncher-10.0.8.jar%2354!/:?] {}
		at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:113) ~[securejarhandler-2.1.4.jar:?] {}
		at cpw.mods.cl.ModuleClassLoader.lambda$findClass$15(ModuleClassLoader.java:219) ~[securejarhandler-2.1.4.jar:?] {}
		at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:229) ~[securejarhandler-2.1.4.jar:?] {}
		at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:219) ~[securejarhandler-2.1.4.jar:?] {}
		at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:135) ~[securejarhandler-2.1.4.jar:?] {}
		at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] {}
		at com.vyklade.ars_armiger.ArsArmiger.setup(ArsArmiger.java:39) ~[arsarmiger-1.19.2-1.1.jar%23584!/:1.19.2-1.1] {re:classloading}
		at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:260) ~[eventbus-6.0.3.jar%2351!/:?] {}
		at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:252) ~[eventbus-6.0.3.jar%2351!/:?] {}
		at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.3.jar%2351!/:?] {}
		at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.3.jar%2351!/:?] {}
		at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:107) ~[javafmllanguage-1.19.2-43.2.4.jar%231011!/:?] {}
		at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:122) ~[fmlcore-1.19.2-43.2.4.jar%231010!/:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
		at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {re:mixin,re:computing_frames}
		at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {re:mixin,re:computing_frames}
		at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {re:mixin}

	Mod File: /home/mch/multicraft/servers/server88159/mods/arsarmiger-1.19.2-1.1.jar
	Failure message: Ars Armiger (ars_armiger) encountered an error during the common_setup event phase
		java.lang.NoClassDefFoundError: net/minecraft/client/gui/GuiComponent
	Mod Version: 1.19.2-1.1
	Mod Issue URL: https://github.com/yoshisman8/ars-armiger/issues
	Exception message: java.lang.ClassNotFoundException: net.minecraft.client.gui.GuiComponent

**Comment by yoshisman8** [comment]
Hmmm, this seems to be when the mod tries to register the new module parts with Tetra, I'll look into it

**Comment by yoshisman8** [comment]
@DeltaWolf7 Issue fixed in v1.2! It should be going live on Curse Forge within the next hour!

**Comment by SmallSansSerif** [comment]
Still getting this server crash on arsarmiger-1.19.2-1.3.3.jar with ars_nouveau-1.19.2-3.12.3.jar 

https://pastebin.com/S6DMrw6D

Server crashes when player attempts to put spell on sword.

From user: "it said can be inscribed with a spell
The sword on the table" "by right click the spell book on the table i can put the spell on the book onto whatever im putting the spell on" "This is the spell" "form arguments is not put on because the sword will use touch by default and cannot be change
[3:58 PM]
the spell are 
-Harm: deal small damage
-Magelight: either make a glowing ball of light, or make mob it hit glow which is what I meant to make"

![image1](https://user-images.githubusercontent.com/4984139/221979851-ee656a0f-aec8-42f7-9667-c97da150ca29.png)
![image2](https://user-images.githubusercontent.com/4984139/221979867-cc97a431-3669-43e1-be91-81ee0d38e99e.png)
![image3](https://user-images.githubusercontent.com/4984139/221979880-c9fe4504-2272-477e-aaac-29a05c99b63b.png)

**Comment by yoshisman8** [comment]
I found the source of the issue, it will be getting fixed in the upcoming update!
